const { resolve } = require('path')
const nodePlop = require('node-plop')
const constants = require('../../../constants')
const prepareFiles = require('../../prepareFiles')
const cleanup = require('../../cleanup')
const processPrompts = require('../../processPrompts')
const successMessages = require('./success')
const installDeps = require('../../installDeps')
const notifyActionsComplete = require('./notifyActionsComplete')
const kleur = require('kleur')

const plopFile = resolve(__dirname, 'plopfile.js')
const plop = nodePlop(plopFile)
const generator = plop.getGenerator('generate')

module.exports = () => (
  cleanup()
    .then(prepareFiles(constants.vanilla))
    .then(generator.runPrompts)
    .then(processPrompts)
    .then(generator.runActions)
    .then(notifyActionsComplete)
    .then(cleanup)
    .then(installDeps)
    .then(successMessages)
    .catch(error => {
      console.warn(kleur.bold.yellow(error))
      process.exit(1)
    })
    .then(cleanup)
)
